# Generated by Django 4.2.4 on 2023-09-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profesor_imagenes/'),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
