# Generated by Django 4.2.4 on 2023-09-10 02:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=0),
            preserve_default=False,
        ),
    ]
