# Generated by Django 4.2.4 on 2023-09-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_entregable_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Cargo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='colaborador_imagenes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
