# Generated by Django 4.2.4 on 2023-09-10 21:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_certificado_colaborador_certificado_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='colaborador',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
