# Generated by Django 4.2.4 on 2023-09-10 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_remove_certificado_colaborador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='imagen',
        ),
    ]
